#!/usr/bin/env bash
#Configures new ubuntu machine with requirements.
apt-get update
apt-get -y install nginx
echo "Holberton School" | sudo tee /usr/share/nginx/html/index.html
service nginx restart
