#!/usr/bin/env bash
#redirecting server to another page
sudo apt-get -y install nginx
echo "Holberton School" | sudo tee /usr/share/nginx/html/index.html
service nginx start
sudo sed -i 'rewrite ^/()$/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4/$1 permanent;' /etc/nginx/sites-available/default
sudo servie nginx restart
