#!/usr/bin/env bash
#redirecting server to another page
apt-get -y update
apt-get -y install nginx
echo "Holberton School" | sudo tee /usr/share/nginx/html/index.html
sed -i "s,server_name _{,location /redirect_me {\n\treturn 301 https://www.youtube.com/watch?v=dQw4w9WgXcQ\n\t};," /etc/nginx/sites-available/default
service nginx restart
