#!/usr/bin/env bash
#redirecting server to another page
apt-get -y update
apt-get -y install nginx
echo "Holberton School" > /var/www/html/index.nginx-debian.html
sed -i "s,server_name _;,server_name _;\n\tlocation /redirect_me {\n\treturn 301 https://www.youtube.com/watch?v=dQw4w9WgXcQ;\n\t}," /etc/nginx/sites-available/default
service nginx restart
