#!/usr/bin/env bash
#Config second server
sudo apt-get update
sudo apt-get -y install nginx
sudo service nginx start
sudo sed -i "s,http {,http\n\tadd_header X-Served-By $HOSTNAME;\n" /etc/nginx/nginx.conf
sudo service nginx restart
