#!/usr/bin/env bash
#Write a Bash script that displays the content of the file /etc/passwd, using the while loop + IFS.

while IFS=: read -r line
do
	USERNAME="${line[0]}"
	GROUP_ID="${line[3]}"
	HOME_DIRECTORY="${line[5]}"
	COMMAND="${line[6]}"
	USER_ID="${line[2]}"
	PASSWORD="${line[1]}"
	USERINFO="${line[4]}"

	echo "The user $USERNAME is part of the $GROUP_ID gang, lives in $HOME_DIRECTORY and rides $COMMAND/SHELL. $USER_ID place is protected by the passcode $PASSWORD, more info about the user here: $USERINFO"

done < /etc/passwd
