#!/usr/bin/env bash
#Write a Bash script that displays the visitor IP along with the HTTP status code from the Apache log file.

if [ -e apache-access.log ]
then
    awk '{ print $1 " " $9}' apache-access.log
fi
