#!/usr/bin/env bash
#Write a Bash script that displays the time for 12 hours and 59 minutes:

minutes=1
hour=0
while [ $hour -le 12 ]
do
      echo "Hour: $hour"
      minutes=1
      while [ $minutes -le 59 ]
      do
      echo $minutes
      ((minutes++))
      done
((hour++))
done
